// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfProjektWirtualnyTaksometr.BazaDanych;

#nullable disable

namespace WpfProjektWirtualnyTaksometr.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250512085152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("WpfProjektWirtualnyTaksometr.Modele.Kierowca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("statusKierowcy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Kierowcy");
                });

            modelBuilder.Entity("WpfProjektWirtualnyTaksometr.Modele.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("WpfProjektWirtualnyTaksometr.Modele.Pojazd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KierowcaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumerRejestracyjny")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KierowcaId");

                    b.ToTable("Pojazdy");
                });

            modelBuilder.Entity("WpfProjektWirtualnyTaksometr.Modele.Przejazd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("KierowcaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Kilometry")
                        .HasColumnType("REAL");

                    b.Property<int>("KlientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PunktKoncowy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PunktStartowy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RodzajPlatnosci")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaryfaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KierowcaId");

                    b.HasIndex("KlientId");

                    b.HasIndex("TaryfaId");

                    b.ToTable("Przejazdy");
                });

            modelBuilder.Entity("WpfProjektWirtualnyTaksometr.Modele.Taryfa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CenaZaKm")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypTaryfa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Taryfy");
                });

            modelBuilder.Entity("WpfProjektWirtualnyTaksometr.Modele.Pojazd", b =>
                {
                    b.HasOne("WpfProjektWirtualnyTaksometr.Modele.Kierowca", "Kierowca")
                        .WithMany("Pojazdy")
                        .HasForeignKey("KierowcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierowca");
                });

            modelBuilder.Entity("WpfProjektWirtualnyTaksometr.Modele.Przejazd", b =>
                {
                    b.HasOne("WpfProjektWirtualnyTaksometr.Modele.Kierowca", "Kierowca")
                        .WithMany("Przejazdy")
                        .HasForeignKey("KierowcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WpfProjektWirtualnyTaksometr.Modele.Klient", "Klient")
                        .WithMany("Przejazdy")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WpfProjektWirtualnyTaksometr.Modele.Taryfa", "Taryfa")
                        .WithMany()
                        .HasForeignKey("TaryfaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierowca");

                    b.Navigation("Klient");

                    b.Navigation("Taryfa");
                });

            modelBuilder.Entity("WpfProjektWirtualnyTaksometr.Modele.Kierowca", b =>
                {
                    b.Navigation("Pojazdy");

                    b.Navigation("Przejazdy");
                });

            modelBuilder.Entity("WpfProjektWirtualnyTaksometr.Modele.Klient", b =>
                {
                    b.Navigation("Przejazdy");
                });
#pragma warning restore 612, 618
        }
    }
}
